modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="dontstarve3"
version="0.1.1"
displayName="DontStarve3"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="ZNM"
description='''
emm...
'''

[[dependencies.dontstarve3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




